hzab/hzab/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('spiderman/', admin.site.urls),
    path('',include("mind.urls")),

]

hzab/mind/urls.py
from django.urls import path
from . import views
app_name = "mind"

urlpatterns = [
    path("",views.index,name="index"),
    path("contact/",views.contact,name="contact"),
    path("officials/",views.officials,name="officials"),
    path("organization/",views.organization,name="organization"),
    path("resources/",views.resources,name="resources"),
    path("vacancy/",views.vacancy,name="vacancy"),
    path('news/',views.news,name="news"),
    path('region/',views.region,name="region"),
    path('news/<int:news_id>/',views.full_news,name="full_news"),
]

hzab/mind/models.py
from django.db import models

# Create your models here.


class News(models.Model):
    news_id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=20)
    body  = models.CharField(max_length=1000)
    newsImage = models.ImageField()
    sources = models.CharField(max_length=50)
    
class ContactMessage(models.Model):
    message = models.CharField(max_length=1000)
    email  = models.EmailField(max_length=50)
    name = models.TextField(max_length=100)
    phone = models.CharField(max_length=16)

hzab/mind/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import News,ContactMessage


def index(request):
    return render(request, 'mind/index.html')

def resources(request):
    return render(request,"mind/resources.html")

# def contact(request):
#     return render(request, 'mind/contact.html')

def vacancy(request):
    return render(request,"mind/vacancy.html")

def resources(request):
    return render(request, 'mind/resources.html')

def officials(request):
    return render(request,"mind/officials.html")

def news(request):
    all_news = News.objects.all()
    return render(request,"mind/news.html",{"all_news":all_news})


def organization(request):
    return render(request,"mind/organizational.html")
def region(request):
    return render(request,'mind/region.html')
def full_news(request,news_id):
    my_news = News.objects.get(news_id=news_id)
    return render(request,"mind/full_news.html",{"my_news":my_news})




# views.py
from django.shortcuts import render
from django.http import HttpResponse

def contact(request):
    if request.method == "POST":
        # Access form fields
        name = request.POST.get("name", "").strip()      
        email = request.POST.get("email", "").strip()
        message = request.POST.get("message", "").strip()
        phone = request.POST.get("phone", "").strip()
        

        errors = []
        if not name:
            errors.append("Name is required.")
        if not email:
            errors.append("Email is required.")
        if not message:
            errors.append("Message is required.")
        if not phone:
            errors.append("add phone number.")

        if errors:

            return render(request, "mind/contact.html", {"errors": errors,
                                                    "name": name,
                                                    "email": email,
                                                    "message": message})

        ContactMessage.objects.create(
            name=name,
            email=email,
            message=message,
            phone=phone,
        )
        return render(request, "mind/contact.html",{"succes":"your form is submited."})

    # GET request → render empty form
    return render(request, "mind/contact.html")

hzab/mind/templates/mind/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>hadiya zone agriculture</title>
    {% load static %}
        <script defer src="{% static 'mind/js/nav.js' %}"></script>
        <script defer src="{% static 'mind/js/intersection.js' %}"></script>
  
    <link rel="stylesheet" href="{% static 'mind/css/bundle.css' %}">
    <link href="https://api.fontshare.com/v2/css?f[]=supreme@300,400,500,700,800&display=swap" rel="stylesheet">

    
  </head>
  <body>

    <section id="header" class=" ">

      <div class="all__header">
        <div class="header__logo">
          <img class="header__logo_image jumpy"  width="64px" hieght="64px" src="{% static 'mind/img/logo.png' %}">
          <p class="header__logo_desc" >Hadiya Zone<br>Departement of<br>Agriculture</p>
        </div>
          <svg class= "jumpy"   height="2rem"    width="2rem" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 5.25h16.5m-16.5 4.5h16.5m-16.5 4.5h16.5m-16.5 4.5h16.5" />
          </svg>
        <ul class="header_ul hidden">
          <li><a class="header__anchor" href="{% url 'mind:index' %}#home">home</a></li>
          <li>
            <button class="header__anchor aboutus__anchor dropbtn" >about us ▼</button>
            <div class="about__us_list sub__list">
              <ul>
                <li><a href="{% url 'mind:officials' %}">our officials</a></li>
                <li><a href="{% url 'mind:region' %}">The region</a></li>
                <li><a href="{% url 'mind:organization' %}">Organizational Structure</a></li>
              </ul>
            </div>
          </li>
          <li><a class="header__anchor" href="{% url 'mind:index' %}#services">Services</a></li>
          <li><a class="header__anchor" href="{% url 'mind:index' %}#programs">Programs</a></li>
          <li>
          <button class="header__anchor resources__anchor dropbtn">resources ▼</button>
          <div class="resources__list sub__list">
            <ul>
              <li><a href="{% url 'mind:resources' %}#img">images</a></li>
              <li><a href="{% url 'mind:resources' %}#doc">Documents</a></li>
            </ul>
          </div>
          </li>
          <li><a class="header__anchor" href="{% url 'mind:news' %}" >news</a></li>
          <li><a class="header__anchor" href="{% url 'mind:contact' %}">Contact</a></li>
          <li>
            <button class="header__anchor announcement__anchor dropbtn" >announcements ▼</button>
            <div class="announcement__list  sub__list">
              
              <ul>
                <li><a href="{% url 'mind:vacancy'%}">vacancy</a></li>
                <li><a></a></li>
              </ul>
            </div>
          </li>
        </ul>

      </div>

{% block body %}
    
    {% endblock body%}

    <section id="contact" class=" ">
          <div class="quick__links">
      <P class="ttl ">Quick Links</P>
      <ul>
        <li><a href="{% url 'mind:index' %}#services">Services</a></li>
        <li><a href="{% url 'mind:index' %}#home">Home</a></li>
       <li> <a href="{% url 'mind:index' %}#programs">programs</a></li>
        <li><a href="{% url 'mind:contact' %}">contact</a></li>
        <li><a href="{% url 'mind:vacancy'%}">vacancy</a></li>
        <li><a href="{% url 'mind:resources' %}#img">images</a></li>
      </ul>
    </div>
    <div class="other__qiuck">

        <div class="hrs__element">
            <div class="hrs__icon">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-phone-icon lucide-phone"><path d="M13.832 16.568a1 1 0 0 0 1.213-.303l.355-.465A2 2 0 0 1 17 15h3a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2A18 18 0 0 1 2 4a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v3a2 2 0 0 1-.8 1.6l-.468.351a1 1 0 0 0-.292 1.233 14 14 0 0 0 6.392 6.384"/></svg>
            </div>
            <div class="hrs_desc">
              <p><span class="ttl ">Phone</span><br>0954342212</p>
            </div>
        </div>
        <div class="hrs__element">
          <div class="hrs__icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-mail-icon lucide-mail"><path d="m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7"/><rect x="2" y="4" width="20" height="16" rx="2"/></svg>
          </div>
          <div class="hrs_desc">
            <p><span class="ttl ">Email</span><br>hossana@gmail.com</p>
          </div>
          
        </div>
        <div class="hrs__element">
          <div class="hrs__icon clock">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-clock2-icon lucide-clock-2"><path d="M12 6v6l4-2"/><circle cx="12" cy="12" r="10"/></svg>
          </div>
          <div class="hrs_desc">
            <p><span class="ttl ">Office Hours</span><br>Mon - Fri: 8:00 AM - 5:00 PM<br>
                Sat: 9:00 AM - 1:00 PM<br>
                Sun: Closed
              </p>
        </div>
      </div>
      <div class="social__container">
        <p class="ttl ">Follow us</p>
        <div class="social__icons">
          <div class="youtube social"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-youtube-icon lucide-youtube"><path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17"/><path d="m10 15 5-3-5-3z"/></svg></div>
          <div class=" twitter social"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-twitter-icon lucide-twitter"><path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z"/></svg></div>
          <div class="facebook social"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-facebook-icon lucide-facebook"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/></svg></div>

        </div>
      </div>
    </div>

    </section>




  </body>
</html>

hzab/mind/templates/mind/contact.html
{% extends "mind/base.html"%}
{% load static %}
{% block body%}



<section class="main container">
      <div class="form__map_container">
          <div class="contact__form">
            {% if errors %}
          <ul style="color:red;">
              {% for error in errors %}
                  <li>{{ error }}</li>
              {% endfor %}
          </ul>
          {% endif %}
          {%if success %}
          <P>{{success}}</P>
          {% endif %}
          <p class="cont__title">Leave us a message</p>
        <form action="{% url 'mind:contact' %}" method="POST">
           {% csrf_token %}
            <div class="email__name__container label__form">
              <div class="name__cont label__form">
                <label for="name">Full Name</label>
                <input type="text" name="name" id="name" required>
              </div>

              <div class="email__cont label__form"> 
                <label for="email">Email</label>
                <input type="email" name="email" id="email" required>
              </div>
            </div>             

            <div class="phone__cont label__form">
              <label for="phone">Phone</label>
              <input type="tel" name="phone" id="phone" placeholder="+251 9XX XXX XXX" required>
            </div>
            
            <div class="message__cont label__form">
              <label for="message">Message</label>
              <textarea name="message" id="message" rows="5" required></textarea>
            </div>
            
            <input type="submit" class="btn submit__form" value="Submit Message">
          </form>
      </div>

      <div class="office__location google__map">
          <p class="cont__title">Visist Our office</p>
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3955.1891744162162!2d37.85478550876211!3d7.554340892427945!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x17b2362e11000001%3A0x9f22892e654a7103!2sHadiya%20Zone%20Rural%20Development%20Office!5e0!3m2!1sen!2set!4v1769805952897!5m2!1sen!2set" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
      </div>
</section>

{% endblock body %}

hzab/mind/templates/mind/full_news.html
{% extends "mind/base.html"%}
{% load static %}
{% block body%}
<div class="container full__news_container">
    <h1 class="full__news_title">{{my_news.title}}</h1>
    <div class="full__news_img">{{my_news.newsImage}}</div>
    <p class="full__news_body">{{my_news.body}}</p>
    <P class="full__news_ref"><section style="font-weight:italic;">@sources</section>{{my_news.sources}}</P>



    
</div>

{% endblock body%}

hzab/mind/templates/mind/index.html
{% extends "mind/base.html"%}
{% load static %}
{% block body %}

    </section>
    <section id="home"     class="container">
      <div class="home__slide_show fill">
      </div>
      <div class="btns_3p__container">
        <img class=" leader__image" width="20rem" src=" {% static 'mind/img/main__leader.jpg' %}" alt="leader">

        <div class="wt__img">
          <div class="p_cont">
              <!-- <div class="timing">
                <p><br>since 1992</p>
              </div> -->
              <p class="message">Message from our leader</p>
              <p class="message__desc">The Hadiya Zone Department of Agriculture modernizes regional farming by distributing Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto eveniet officiis magnam tenetur fugiat nam esse placeat, perferendis nesciunt error, accusamus fugit corrupti incidunt facere voluptatem consequatur illum, lorem300 porro quae! seeds and fertilizers, providing technical extension services, lorem60
                managing natural resources, and enhancing livestock productivity to ensure community food security.</p>
          </div>
          <div class="btns__container">
            <button class="exp__services btn"><a href="{% url 'mind:index' %}#services">Explore Services</a></button>
            <button class="contact__us btn"><a href="{% url 'mind:contact' %}">Contact Us</a></button>
          </div>
        </div>
      </div>

      <div class="icon__display"> 
        <div>
            <p>350,000+<br><span>Farmers</span></p>
          </div>
        <div> 
          <p>310+<br><span>Kebele</span></p>
        </div>
        <div> 
          <p>30+ <br> <span>Years</span></p>
        </div>
        <div>
          <p><br>47% <br><span>Crop Yield improvement</span></p>
          </div>

      </div>
    
    </section>
    <section id="services"  class="container ">
      <div>
        <p class="section__title">Our Services</p>
        <p>The department supports these thousands of households through a network of Development Agents (DAs) 
          stationed at the kebele (village) level to provide direct training and resources.</p>
      </div>
      <div class="service__card__container">
        <div class="service__card crop__advisory">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-sprout-icon lucide-sprout"><path d="M14 9.536V7a4 4 0 0 1 4-4h1.5a.5.5 0 0 1 .5.5V5a4 4 0 0 1-4 4 4 4 0 0 0-4 4c0 2 1 3 1 5a5 5 0 0 1-1 3"/><path d="M4 9a5 5 0 0 1 8 4 5 5 0 0 1-8-4"/><path d="M5 21h14"/></svg>
          <P class="service__title">Crop Advisory</P>
          <p>Expert guidance on crop selection, planting schedules, and best practices for optimal yields.<br></p>
        </div>
        <div class="service__card ">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-book-open-icon lucide-book-open"><path d="M12 7v14"/><path d="M3 18a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h5a4 4 0 0 1 4 4 4 4 0 0 1 4-4h5a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-6a3 3 0 0 0-3 3 3 3 0 0 0-3-3z"/></svg>
          <P class="service__title">Training & Education</P>
          <p>Workshops, seminars, and courses to enhance farming skills and knowledge of modern techniques.</p>
        </div>
        <div class="service__card">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-users-round-icon lucide-users-round"><path d="M18 21a8 8 0 0 0-16 0"/><circle cx="10" cy="8" r="5"/><path d="M22 20c0-3.37-2-6.5-4-8a5 5 0 0 0-.45-8.3"/></svg>
          <P class="service__title">Farmer Cooperatives</P>
          <p>Support for forming and managing cooperative groups to improve market access and bargaining power.</p>
        </div>
        <div class="service__card">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-dollar-sign-icon lucide-circle-dollar-sign"><circle cx="12" cy="12" r="10"/><path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"/><path d="M12 18V6"/></svg>
          <P class="service__title">Market Information</P>
          <p>Real-time market prices, demand forecasts, and buyer connections for better sales opportunities.</p>
        </div>
        <div class="service__card">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-copyright-icon lucide-copyright"><circle cx="12" cy="12" r="10"/><path d="M14.83 14.83a4 4 0 1 1 0-5.66"/></svg>
          <P class="service__title">Permit & Licensing</P>
          <p>Assistance with agricultural permits, certifications, and regulatory compliance.</p>
        </div>
        <div class="service__card">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-blocks-icon lucide-blocks"><path d="M10 22V7a1 1 0 0 0-1-1H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-5a1 1 0 0 0-1-1H2"/><rect x="14" y="2" width="8" height="8" rx="1"/></svg>
          <P class="service__title">Extension Services</P>
          <p>On-site support from agricultural extension officers for personalized farm management.</p>
        </div>
        

      </div>
    </section>
    <section id="programs"  class="container ">

      <p class="section__title">Featured Programs</p>
      <p>Specialized programs designed to address specific needs and opportunities in modern agriculture</p>

      <div class="programs__card__container">
        <div class="programs__card">
          <img src="{% static 'mind/img/landmanagment.jpg' %}">
          <div>
            <p class="program__title">Sustainable Land Management Program (SLMP)</p>
            <p>Teams build terraces and plant conservation grasses to prevent soil erosion and restore degraded highland environments.</p>
            <a>Learn more</a>
          </div>
        </div>
        <div class="programs__card">
          <img src="{%static 'mind/img/safetynet.jpg'%}">
          <div>
            <p class="program__title">Productive Safety Net Program</p>
            <p>Vulnerable households receive food or cash in exchange for labor on vital community infrastructure projects.</p>
            <a>Learn more</a>
          </div> 
        </div>
        <div class="programs__card">
          <img src="{% static 'mind/img/livestock.jpg' %}">
          <div>
            <p class="program__title">Livestock and Forage Development</p>
            <p>The bureau introduces improved animal feed and veterinary services to boost milk and meat production.</p>
            <a>Learn more</a>
          </div>
        </div>
      </div>
      
    </section>



{%endblock body%}

hzab/mind/templates/mind/news.html
{% extends "mind/base.html" %}
{% load static %}
{% block body%}
    <section>

         <div id="news" class="news__card__container">
            <div class="news__card">
                <div class="news__top_title" ><p lang="am">ዜና</p></div>
                <img src="{% static 'mind/img/landmanagment.jpg' %}">
                <div class="news__desc">
                    <p class="news__title">Sustainable Land Management Program (SLMP)</p>
                    <p>Teams build terraces and plant conservation grasses to prevent soil erosion and restore degraded highland environments.</p>
                    <a>Learn more</a>
                </div>
              </div>
            <div class="news__card">
                <div class="news__top_title" ><p lang="am">News Title</p></div>
                <img src="{% static 'mind/img/landmanagment.jpg' %}">
                <div class="news__desc">
                    <p class="news__title">Sustainable Land Management Program (SLMP)</p>
                    <p>Teams build terraces and plant conservation grasses to prevent soil erosion and restore degraded highland environments.</p>
                    <a>Learn more</a>
                </div>
            </div>
            <div >
            {% for news in all_news %}

            <a style="color:black; display:block;" href="{% url 'mind:full_news' news.news_id %}">{{news.title}}</a>
            {% endfor %}
          </div>

            </section>

{% endblock body %}

hzab/mind/templates/mind/officials.html
{% extends "mind/base.html" %}
{% load static %}
{% block body%}

    
 
<section class="container leaders">
  <P class="officials__title">Head of HZAB</P>
    <div class="official__card main__leader">
        <div class="official__image "><img src="{% static 'mind/img/main__leader.jpg'%}"></div>
        <div class="official__desc">
            <p class="official__position">Finance</p>
            <p class="official__name">Ato Kebede Menchore</p>
            <p class="official__sector">Livestock and polutary sector adminstrator</p>
        </div>
         </div>
    <P class="officials__title">SubHeads of HZAB</P>

    <div class="sub__leaders">
          <div class="official__card main__leader hide" >
          <div class="official__image"><img src="{% static 'mind/img/main__leader.jpg' %}"></div>
          <div class="official__desc">
              <p class="official__position">Finance</p>
              <p class="official__name">Ato Kebede Menchore</p>
              <p class="official__sector">Livestock and polutary sector adminstrator</p>
          </div>
         </div>
      <div class="official__card main__leader hide" >
          <div class="official__image"><img src="{% static 'mind/img/main__leader.jpg'%}"></div>
          <div class="official__desc">
              <p class="official__position">Finance</p>
              <p class="official__name">Ato Kebede Menchore</p>
              <p class="official__sector">Livestock and polutary sector adminstrator</p>
          </div>
          </div>
    <div class="official__card main__leader  hide" >
        <div class="official__image"><img src="{% static 'mind/img/main__leader.jpg'%}"></div>
        <div class="official__desc">
            <p class="official__position">Finance</p>
            <p class="official__name">Ato Kebede Menchore</p>
            <p class="official__sector">Livestock and polutary sector adminstrator</p>
        </div>
         </div>

</section>


    </div>

  {% endblock body%}

hzab/mind/templates/mind/organizational.html
{% extends "mind/base.html" %}
{% load static %}
{% block body%} 
  <section class="container region__container">
    <div class="org__str_cont">
      <img src="{% static 'mind/img/hzos.png'%}" width="100%" height="auto">
    </div>
  </section>
{% endblock body%}

hzab/mind/templates/mind/region.html
{% extends "mind/base.html" %}
{% load static %}
{% block body %}
    <section class="container region__container">
      <div class="region__img ce__img collect">
        <img src="{% static 'mind/img/ze.svg'%}" width="352px" height="auto">
        <div class="ce__img_desc">
          <p>The Hadiya Zone is located in the Central Ethiopia Regional State, approximately 230 kilometers southwest of Addis Ababa. Geographically situated in the western Ethiopian highlands, it serves as a vital agricultural hub. Its administrative center, Hosanna, sits at a high elevation, enjoying a temperate climate ideal for diverse crop production.</p>
        </div>
      </div>
    </section>

    
    {% endblock body %}

hzab/mind/templates/mind/resources.html
{% extends "mind/base.html" %}
{% load static %}
{% block body%}
    <div id="img" class="res__img_container container">
        <img width="320px" hieght="320px" src="{% static 'mind/img/banana.jpg'%}">
        <img width="320px" hieght="320px" src="{% static 'mind/img/holding_tomato.jpg'%}">
        <img width="320px" hieght="320px" src="{% static 'mind/img/clear_mango.jpg'%}">
        <img width="320px" hieght="320px" src="{% static 'mind/img/observing.jpg'%}">
        <img width="320px" hieght="320px" src="{% static 'mind/img/baner.jpg'%}">
        <img width="320px" hieght="320px" src="{% static 'mind/img/safetynet.jpg'%}">
        <img width="320px" hieght="320px" src="{% static 'mind/img/livestock.jpg'%}">
        <img width="320px" hieght="320px" src="{% static 'mind/img/onion.jpg'%}">
    </div>
   <div id="doc" class="res__pdf container">
    <div class="pdf-grid">
        <div class="pdf-card">
            <h3>Farmer Adaptation Guide</h3>
            <p>detail study</p>
            <a href="public/pdf/hza.pdf" download="farmer__adaptaion" class="download-btn">Download PDF</a>
        </div>

        <div class="pdf-card">
            <h3>Farmer Adaptation Guide</h3>
            <p>detail study</p>
            <a href="public/pdf/hza.pdf" download="farmer__adaptation" class="download-btn">Download PDF</a>
        </div>

        <div class="pdf-card">
            <h3>Farmer Adaptation Guide</h3>
            <p>detail study</p>
            <a href="public/pdf/hza.pdf" download="farmer__adaptation" class="download-btn">Download PDF</a>
        </div>
    </div>
   </div>

{% endblock body%}

hzab/mind/templates/mind/vacancy.html
{% extends "mind/base.html" %}

{% block body%}
<section class="container jobs">
    <div class="vacancy__card">
        <p class="Vacany__card_position">Position: <span>Agronomist</span></p>
        <div class="vacancy__card_req">
        <P>Pay: <span>12,000 before tax</span> </P>
        <p>Sex: <span>Female</span></p>
        <p>Qualification: <span>diploma in Agriculture</span> </p>
        </div>
    </div>
        <div class="vacancy__card">
        <p class="Vacany__card_position">Position: <span>Accountant</span></p>
        <div class="vacancy__card_req">
        <P>Pay: <span>9,000 before tax</span> </P>
        <p>Sex: <span>Male</span></p>
        <p>Qualification: <span>bachelores in Accounting and related fields.</span> </p>
        </div>
    </div>
        <div class="vacancy__card">
        <p class="Vacany__card_position">Position: <span>Sales Women</span></p>
        <div class="vacancy__card_req">
        <P>Pay: <span>12,000 before tax</span> </P>
        <p>Sex: <span>Male</span></p>
        <p>Qualification: <span>bachelores in Marketing</span> </p>
        </div>
    </div>
</section>
    

    {% endblock body%}